### ISSUE TITLE
Let's Encrypt自動更新されない 

### ISSUE THREAD

**Issue by luckyriver0** [HanaLucky/KPTer-web#153]
cronが動いていなかった。
手動で証明書更新するも、さらに追い討ちでエラー。
どうやらこれにぶち当たった。→https://github.com/certbot/certbot/issues/2823
記載の通りに実施し、解消。

あとはcronの設定をなんとかする。

**Comment by luckyriver0** [comment]
`/etc/cron.daily/letsencrypt`のファイルを作成しdailyで動かすように仕込んでみた。

letsencryptの中身は以下。

```
#!/bin/sh

1 * * * * root /usr/local/bin/certbot/certbot-auto renew --debug && service httpd graceful >> /var/log/certbot-renew.log 2>&1

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    echo Automated renewal failed:
    exit 1
fi

service httpd graceful
```

翌日動いているか、確認。

**Comment by luckyriver0** [comment]
what happen...?

```
[root@ip ~]# /usr/local/bin/certbot/certbot-auto renew --debug
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
```

https://community.letsencrypt.org/t/certbot-auto-renew-error/29584

...hum

remove letsencrypt.

```
[root@ip ~]# rm -rf /root/.local/share/letsencrypt
```

and, retry.

```
[root@ip ~]# /usr/local/bin/certbot/certbot-auto renew --debug
Bootstrapping dependencies via Amazon Linux...
yum is /usr/bin/yum
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                          | 2.1 kB     00:00
amzn-updates/latest                                                                                       | 2.3 kB     00:00
Package gcc-4.8.3-3.20.amzn1.noarch already installed and latest version
Package augeas-libs-1.0.0-5.7.amzn1.x86_64 already installed and latest version
Package python27-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-devel-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-tools-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package 1:mod_ssl-2.2.31-1.8.amzn1.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package ca-certificates.noarch 0:2015.2.6-65.0.1.15.amzn1 will be updated
---> Package ca-certificates.noarch 0:2015.2.6-65.0.1.16.amzn1 will be an update
---> Package libffi-devel.x86_64 0:3.0.13-11.4.amzn1 will be updated
---> Package libffi-devel.x86_64 0:3.0.13-16.5.amzn1 will be an update
--> Processing Dependency: libffi = 3.0.13-16.5.amzn1 for package: libffi-devel-3.0.13-16.5.amzn1.x86_64
---> Package openssl.x86_64 1:1.0.1k-15.93.amzn1 will be updated
---> Package openssl.x86_64 1:1.0.1k-15.99.amzn1 will be an update
---> Package openssl-devel.x86_64 1:1.0.1k-15.93.amzn1 will be updated
---> Package openssl-devel.x86_64 1:1.0.1k-15.99.amzn1 will be an update
---> Package python27-pip.noarch 0:6.1.1-1.21.amzn1 will be updated
---> Package python27-pip.noarch 0:6.1.1-1.23.amzn1 will be an update
---> Package python27-virtualenv.noarch 0:12.0.7-1.12.amzn1 will be updated
---> Package python27-virtualenv.noarch 0:12.0.7-1.13.amzn1 will be an update
---> Package system-rpm-config.noarch 0:9.0.3-42.27.amzn1 will be updated
---> Package system-rpm-config.noarch 0:9.0.3-42.28.amzn1 will be an update
--> Running transaction check
---> Package libffi.x86_64 0:3.0.13-11.4.amzn1 will be updated
---> Package libffi.x86_64 0:3.0.13-16.5.amzn1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================
 Package                           Arch                 Version                                 Repository                  Size
=================================================================================================================================
Updating:
 ca-certificates                   noarch               2015.2.6-65.0.1.16.amzn1                amzn-main                  1.3 M
 libffi-devel                      x86_64               3.0.13-16.5.amzn1                       amzn-main                   23 k
 openssl                           x86_64               1:1.0.1k-15.99.amzn1                    amzn-updates               1.6 M
 openssl-devel                     x86_64               1:1.0.1k-15.99.amzn1                    amzn-updates               1.5 M
 python27-pip                      noarch               6.1.1-1.23.amzn1                        amzn-main                  1.9 M
 python27-virtualenv               noarch               12.0.7-1.13.amzn1                       amzn-main                  2.0 M
 system-rpm-config                 noarch               9.0.3-42.28.amzn1                       amzn-updates                63 k
Updating for dependencies:
 libffi                            x86_64               3.0.13-16.5.amzn1                       amzn-main                   31 k

Transaction Summary
=================================================================================================================================
Upgrade  7 Packages (+1 Dependent package)

Total download size: 8.4 M
Is this ok [y/d/N]: y
Downloading packages:
(1/8): ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch.rpm                                                | 1.3 MB     00:00
(2/8): libffi-3.0.13-16.5.amzn1.x86_64.rpm                                                                |  31 kB     00:00
(3/8): libffi-devel-3.0.13-16.5.amzn1.x86_64.rpm                                                          |  23 kB     00:00
(4/8): openssl-1.0.1k-15.99.amzn1.x86_64.rpm                                                              | 1.6 MB     00:00
(5/8): openssl-devel-1.0.1k-15.99.amzn1.x86_64.rpm                                                        | 1.5 MB     00:00
(6/8): python27-pip-6.1.1-1.23.amzn1.noarch.rpm                                                           | 1.9 MB     00:00
(7/8): python27-virtualenv-12.0.7-1.13.amzn1.noarch.rpm                                                   | 2.0 MB     00:00
(8/8): system-rpm-config-9.0.3-42.28.amzn1.noarch.rpm                                                     |  63 kB     00:00
---------------------------------------------------------------------------------------------------------------------------------
Total                                                                                             22 MB/s | 8.4 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : 1:openssl-1.0.1k-15.99.amzn1.x86_64                                                                          1/16
  Updating   : ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch                                                              2/16
  Updating   : python27-pip-6.1.1-1.23.amzn1.noarch                                                                         3/16
  Updating   : libffi-3.0.13-16.5.amzn1.x86_64                                                                              4/16
  Updating   : libffi-devel-3.0.13-16.5.amzn1.x86_64                                                                        5/16
  Updating   : python27-virtualenv-12.0.7-1.13.amzn1.noarch                                                                 6/16
  Updating   : 1:openssl-devel-1.0.1k-15.99.amzn1.x86_64                                                                    7/16
  Updating   : system-rpm-config-9.0.3-42.28.amzn1.noarch                                                                   8/16
  Cleanup    : python27-virtualenv-12.0.7-1.12.amzn1.noarch                                                                 9/16
  Cleanup    : python27-pip-6.1.1-1.21.amzn1.noarch                                                                        10/16
  Cleanup    : 1:openssl-devel-1.0.1k-15.93.amzn1.x86_64                                                                   11/16
  Cleanup    : libffi-devel-3.0.13-11.4.amzn1.x86_64                                                                       12/16
  Cleanup    : ca-certificates-2015.2.6-65.0.1.15.amzn1.noarch                                                             13/16
  Cleanup    : system-rpm-config-9.0.3-42.27.amzn1.noarch                                                                  14/16
  Cleanup    : libffi-3.0.13-11.4.amzn1.x86_64                                                                             15/16
  Cleanup    : 1:openssl-1.0.1k-15.93.amzn1.x86_64                                                                         16/16
  Verifying  : python27-pip-6.1.1-1.23.amzn1.noarch                                                                         1/16
  Verifying  : libffi-devel-3.0.13-16.5.amzn1.x86_64                                                                        2/16
  Verifying  : libffi-3.0.13-16.5.amzn1.x86_64                                                                              3/16
  Verifying  : 1:openssl-devel-1.0.1k-15.99.amzn1.x86_64                                                                    4/16
  Verifying  : ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch                                                              5/16
  Verifying  : python27-virtualenv-12.0.7-1.13.amzn1.noarch                                                                 6/16
  Verifying  : system-rpm-config-9.0.3-42.28.amzn1.noarch                                                                   7/16
  Verifying  : 1:openssl-1.0.1k-15.99.amzn1.x86_64                                                                          8/16
  Verifying  : system-rpm-config-9.0.3-42.27.amzn1.noarch                                                                   9/16
  Verifying  : 1:openssl-devel-1.0.1k-15.93.amzn1.x86_64                                                                   10/16
  Verifying  : python27-pip-6.1.1-1.21.amzn1.noarch                                                                        11/16
  Verifying  : 1:openssl-1.0.1k-15.93.amzn1.x86_64                                                                         12/16
  Verifying  : libffi-3.0.13-11.4.amzn1.x86_64                                                                             13/16
  Verifying  : libffi-devel-3.0.13-11.4.amzn1.x86_64                                                                       14/16
  Verifying  : ca-certificates-2015.2.6-65.0.1.15.amzn1.noarch                                                             15/16
  Verifying  : python27-virtualenv-12.0.7-1.12.amzn1.noarch                                                                16/16

Updated:
  ca-certificates.noarch 0:2015.2.6-65.0.1.16.amzn1                libffi-devel.x86_64 0:3.0.13-16.5.amzn1
  openssl.x86_64 1:1.0.1k-15.99.amzn1                              openssl-devel.x86_64 1:1.0.1k-15.99.amzn1
  python27-pip.noarch 0:6.1.1-1.23.amzn1                           python27-virtualenv.noarch 0:12.0.7-1.13.amzn1
  system-rpm-config.noarch 0:9.0.3-42.28.amzn1

Dependency Updated:
  libffi.x86_64 0:3.0.13-16.5.amzn1

Complete!
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/foobar.net-0002.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for foobar.net
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0009_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0009_csr-certbot.pem

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/foobar.net-0002/fullchain.pem
-------------------------------------------------------------------------------

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/foobar.net-0002/fullchain.pem (success)
```

ok

**Comment by luckyriver0** [comment]
What happen...?

```
[root@ip ~]# /usr/local/bin/certbot/certbot-auto renew --debug
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
```

https://community.letsencrypt.org/t/certbot-auto-renew-error/29584

...hmmm

remove letsencrypt.

```
[root@ip ~]# rm -rf /root/.local/share/letsencrypt
```

and, retry.

```
[root@ip ~]# /usr/local/bin/certbot/certbot-auto renew --debug
Bootstrapping dependencies via Amazon Linux...
yum is /usr/bin/yum
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                          | 2.1 kB     00:00
amzn-updates/latest                                                                                       | 2.3 kB     00:00
Package gcc-4.8.3-3.20.amzn1.noarch already installed and latest version
Package augeas-libs-1.0.0-5.7.amzn1.x86_64 already installed and latest version
Package python27-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-devel-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-tools-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package 1:mod_ssl-2.2.31-1.8.amzn1.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package ca-certificates.noarch 0:2015.2.6-65.0.1.15.amzn1 will be updated
---> Package ca-certificates.noarch 0:2015.2.6-65.0.1.16.amzn1 will be an update
---> Package libffi-devel.x86_64 0:3.0.13-11.4.amzn1 will be updated
---> Package libffi-devel.x86_64 0:3.0.13-16.5.amzn1 will be an update
--> Processing Dependency: libffi = 3.0.13-16.5.amzn1 for package: libffi-devel-3.0.13-16.5.amzn1.x86_64
---> Package openssl.x86_64 1:1.0.1k-15.93.amzn1 will be updated
---> Package openssl.x86_64 1:1.0.1k-15.99.amzn1 will be an update
---> Package openssl-devel.x86_64 1:1.0.1k-15.93.amzn1 will be updated
---> Package openssl-devel.x86_64 1:1.0.1k-15.99.amzn1 will be an update
---> Package python27-pip.noarch 0:6.1.1-1.21.amzn1 will be updated
---> Package python27-pip.noarch 0:6.1.1-1.23.amzn1 will be an update
---> Package python27-virtualenv.noarch 0:12.0.7-1.12.amzn1 will be updated
---> Package python27-virtualenv.noarch 0:12.0.7-1.13.amzn1 will be an update
---> Package system-rpm-config.noarch 0:9.0.3-42.27.amzn1 will be updated
---> Package system-rpm-config.noarch 0:9.0.3-42.28.amzn1 will be an update
--> Running transaction check
---> Package libffi.x86_64 0:3.0.13-11.4.amzn1 will be updated
---> Package libffi.x86_64 0:3.0.13-16.5.amzn1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================
 Package                           Arch                 Version                                 Repository                  Size
=================================================================================================================================
Updating:
 ca-certificates                   noarch               2015.2.6-65.0.1.16.amzn1                amzn-main                  1.3 M
 libffi-devel                      x86_64               3.0.13-16.5.amzn1                       amzn-main                   23 k
 openssl                           x86_64               1:1.0.1k-15.99.amzn1                    amzn-updates               1.6 M
 openssl-devel                     x86_64               1:1.0.1k-15.99.amzn1                    amzn-updates               1.5 M
 python27-pip                      noarch               6.1.1-1.23.amzn1                        amzn-main                  1.9 M
 python27-virtualenv               noarch               12.0.7-1.13.amzn1                       amzn-main                  2.0 M
 system-rpm-config                 noarch               9.0.3-42.28.amzn1                       amzn-updates                63 k
Updating for dependencies:
 libffi                            x86_64               3.0.13-16.5.amzn1                       amzn-main                   31 k

Transaction Summary
=================================================================================================================================
Upgrade  7 Packages (+1 Dependent package)

Total download size: 8.4 M
Is this ok [y/d/N]: y
Downloading packages:
(1/8): ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch.rpm                                                | 1.3 MB     00:00
(2/8): libffi-3.0.13-16.5.amzn1.x86_64.rpm                                                                |  31 kB     00:00
(3/8): libffi-devel-3.0.13-16.5.amzn1.x86_64.rpm                                                          |  23 kB     00:00
(4/8): openssl-1.0.1k-15.99.amzn1.x86_64.rpm                                                              | 1.6 MB     00:00
(5/8): openssl-devel-1.0.1k-15.99.amzn1.x86_64.rpm                                                        | 1.5 MB     00:00
(6/8): python27-pip-6.1.1-1.23.amzn1.noarch.rpm                                                           | 1.9 MB     00:00
(7/8): python27-virtualenv-12.0.7-1.13.amzn1.noarch.rpm                                                   | 2.0 MB     00:00
(8/8): system-rpm-config-9.0.3-42.28.amzn1.noarch.rpm                                                     |  63 kB     00:00
---------------------------------------------------------------------------------------------------------------------------------
Total                                                                                             22 MB/s | 8.4 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : 1:openssl-1.0.1k-15.99.amzn1.x86_64                                                                          1/16
  Updating   : ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch                                                              2/16
  Updating   : python27-pip-6.1.1-1.23.amzn1.noarch                                                                         3/16
  Updating   : libffi-3.0.13-16.5.amzn1.x86_64                                                                              4/16
  Updating   : libffi-devel-3.0.13-16.5.amzn1.x86_64                                                                        5/16
  Updating   : python27-virtualenv-12.0.7-1.13.amzn1.noarch                                                                 6/16
  Updating   : 1:openssl-devel-1.0.1k-15.99.amzn1.x86_64                                                                    7/16
  Updating   : system-rpm-config-9.0.3-42.28.amzn1.noarch                                                                   8/16
  Cleanup    : python27-virtualenv-12.0.7-1.12.amzn1.noarch                                                                 9/16
  Cleanup    : python27-pip-6.1.1-1.21.amzn1.noarch                                                                        10/16
  Cleanup    : 1:openssl-devel-1.0.1k-15.93.amzn1.x86_64                                                                   11/16
  Cleanup    : libffi-devel-3.0.13-11.4.amzn1.x86_64                                                                       12/16
  Cleanup    : ca-certificates-2015.2.6-65.0.1.15.amzn1.noarch                                                             13/16
  Cleanup    : system-rpm-config-9.0.3-42.27.amzn1.noarch                                                                  14/16
  Cleanup    : libffi-3.0.13-11.4.amzn1.x86_64                                                                             15/16
  Cleanup    : 1:openssl-1.0.1k-15.93.amzn1.x86_64                                                                         16/16
  Verifying  : python27-pip-6.1.1-1.23.amzn1.noarch                                                                         1/16
  Verifying  : libffi-devel-3.0.13-16.5.amzn1.x86_64                                                                        2/16
  Verifying  : libffi-3.0.13-16.5.amzn1.x86_64                                                                              3/16
  Verifying  : 1:openssl-devel-1.0.1k-15.99.amzn1.x86_64                                                                    4/16
  Verifying  : ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch                                                              5/16
  Verifying  : python27-virtualenv-12.0.7-1.13.amzn1.noarch                                                                 6/16
  Verifying  : system-rpm-config-9.0.3-42.28.amzn1.noarch                                                                   7/16
  Verifying  : 1:openssl-1.0.1k-15.99.amzn1.x86_64                                                                          8/16
  Verifying  : system-rpm-config-9.0.3-42.27.amzn1.noarch                                                                   9/16
  Verifying  : 1:openssl-devel-1.0.1k-15.93.amzn1.x86_64                                                                   10/16
  Verifying  : python27-pip-6.1.1-1.21.amzn1.noarch                                                                        11/16
  Verifying  : 1:openssl-1.0.1k-15.93.amzn1.x86_64                                                                         12/16
  Verifying  : libffi-3.0.13-11.4.amzn1.x86_64                                                                             13/16
  Verifying  : libffi-devel-3.0.13-11.4.amzn1.x86_64                                                                       14/16
  Verifying  : ca-certificates-2015.2.6-65.0.1.15.amzn1.noarch                                                             15/16
  Verifying  : python27-virtualenv-12.0.7-1.12.amzn1.noarch                                                                16/16

Updated:
  ca-certificates.noarch 0:2015.2.6-65.0.1.16.amzn1                libffi-devel.x86_64 0:3.0.13-16.5.amzn1
  openssl.x86_64 1:1.0.1k-15.99.amzn1                              openssl-devel.x86_64 1:1.0.1k-15.99.amzn1
  python27-pip.noarch 0:6.1.1-1.23.amzn1                           python27-virtualenv.noarch 0:12.0.7-1.13.amzn1
  system-rpm-config.noarch 0:9.0.3-42.28.amzn1

Dependency Updated:
  libffi.x86_64 0:3.0.13-16.5.amzn1

Complete!
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/foobar.net-0002.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for foobar.net
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0009_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0009_csr-certbot.pem

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/foobar.net-0002/fullchain.pem
-------------------------------------------------------------------------------

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/foobar.net-0002/fullchain.pem (success)
```

ok
