### ISSUE TITLE
本番環境でRedisを上手く連携させる

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#306]
```
/usr/local/bundle/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
Exiting
24: from /usr/local/bundle/gems/actioncable-5.2.0/lib/action_cable/subscription_adapter/redis.rb:152:in `block in ensure_listener_running'
23: from /usr/local/bundle/gems/actioncable-5.2.0/lib/action_cable/subscription_adapter/redis.rb:78:in `listen'
22: from /usr/local/bundle/gems/redis-4.0.1/lib/redis.rb:57:in `without_reconnect'
21: from /usr/local/bundle/gems/redis-4.0.1/lib/redis.rb:50:in `with_reconnect'
20: from /usr/local/bundle/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
```

**Comment by hanaori** [comment]
cable.ymlにてasync設定にしたため、Redisは不要になった。
